---

- name: Base Configuration
  hosts: webServers #changed here
  gather_facts: false
  become: true
  tasks:

    - name: Install EPEL
      yum:
        name: epel-release
        state: latest

    - name: Update Server
      yum:
        name: "*"
        state: latest

    - name: Add developer user
      user:
        name: developer
        comment: Developer user

    - name: Add SSH Key Login
      authorized_key:
        user: "{{ansible_user}}"
        state: present
        key: "{{lookup('file', '{{playbook_dir}}/../sshKeyPair/interactive.pub')}} "

    - name: Install screen and tcpump
      yum:
        name: ['screen', 'tcpdump']
        state: latest

    - name: Set hostname
      hostname:
        name: "{{ansible_host}}"
